# Используем официальный образ Nginx
FROM nginx:latest

# Копируем конфигурационный файл Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Копируем статические файлы Django
COPY ./static /var/www/static/
